import { Hono } from "hono";
import { auditRoutes } from "./audits";
import { alertRoutes } from "./alerts";
import { authRoutes } from "./auth";
import { budgetRoutes } from "./budgets";
import { exportRoutes } from "./exports";
import { healthRoutes } from "./health";
import { identityRoutes } from "./identity";
import { integrationCallbackRoutes } from "./integration-callbacks";
import { mcpRoutes } from "./mcp";
import { openPlatformRoutes } from "./open-platform";
import { pricingRoutes } from "./pricing";
import { qualityRoutes } from "./quality";
import { replayRoutes } from "./replay";
import { residencyRoutes } from "./residency";
import { ruleRoutes } from "./rules";
import { sessionRoutes } from "./sessions";
import { sourceRoutes } from "./sources";
import { systemConfigRoutes } from "./system-config";
import { tokenPulseRuntimeRoutes } from "./tokenpulse-runtime";
import { usageRoutes } from "./usage";
import type { AppEnv } from "../types";

export const apiV1Routes = new Hono<AppEnv>();

apiV1Routes.route("/", healthRoutes);
apiV1Routes.route("/", sourceRoutes);
apiV1Routes.route("/", sessionRoutes);
apiV1Routes.route("/", exportRoutes);
apiV1Routes.route("/", usageRoutes);
apiV1Routes.route("/", pricingRoutes);
apiV1Routes.route("/", systemConfigRoutes);
apiV1Routes.route("/", budgetRoutes);
apiV1Routes.route("/", alertRoutes);
apiV1Routes.route("/", residencyRoutes);
apiV1Routes.route("/", ruleRoutes);
apiV1Routes.route("/", mcpRoutes);
apiV1Routes.route("/", openPlatformRoutes);
apiV1Routes.route("/", qualityRoutes);
apiV1Routes.route("/", replayRoutes);
apiV1Routes.route("/", integrationCallbackRoutes);
apiV1Routes.route("/", tokenPulseRuntimeRoutes);
apiV1Routes.route("/", auditRoutes);
apiV1Routes.route("/auth", authRoutes);
apiV1Routes.route("/", identityRoutes);
